# Generated by Django 5.1.3 on 2024-12-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TempMonitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposensor',
            name='descricao',
            field=models.CharField(blank=True, default='Sem descrição', max_length=150),
        ),
    ]
