# Generated by Django 5.1.3 on 2024-12-09 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TempMonitor', '0002_alter_tiposensor_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orientacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pavimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('sigla', models.CharField(max_length=10)),
                ('id_orientacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TempMonitor.orientacao')),
                ('id_pavimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TempMonitor.pavimento')),
            ],
        ),
    ]
